import Head from 'next/head'
import Footer from '../components/Footer'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className='h-[50vh] p-8'>
				<div>Hey</div>
			</main>

			<Footer />
		</div>
	)
}
